# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals ZURI

steps:
  - script: java -version
    displayName: "Verificar versión de Java usada por el agente"

  - script: ./gradlew clean
    displayName: "Limpiar proyecto"

  - script: ./gradlew assembleDebug
    displayName: "Compilar APK Debug"

  # Si quieres release:
  # - script: ./gradlew assembleRelease
  #   displayName: "Compilar APK Release"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '**/*.apk'
      ArtifactName: 'android-build'
      publishLocation: 'Container'
    displayName: "Publicar APK"
