# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals ZURI

steps:
  - script: java -version
    displayName: "Verificar versión de Java"

  - script: echo "CI ejecutado correctamente — Sin compilación de APK"
    displayName: "Mensaje"

  - script: dir
    displayName: "Listar archivos del repositorio"

  - script: type app\build.gradle || type app/build.gradle
    displayName: "Mostrar gradle del módulo (si existe)"
    continueOnError: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '**/*.apk'
      ArtifactName: 'android-build'
      publishLocation: 'Container'
    displayName: "Publicar APK"
    continueOnError: true
